=== Aminos7/XML-Database-Mobilit-/ProjetDTD.dtd
<!ELEMENT Mobilités (offre+)>
<!ELEMENT offre (Ecolepartenaire, Option+, Observation)>
<!ELEMENT Ecolepartenaire (#PCDATA)>
<!ELEMENT Option (Parcours, NbPlaces, TypeMobilité, INPT, Observation?)>
<!ELEMENT Parcours (#PCDATA)>
<!ELEMENT NbPlaces (#PCDATA)>
<!ELEMENT TypeMobilité (#PCDATA)>
<!ELEMENT INPT (filliere+)>
<!ELEMENT filliere (nomfil, etudiant+)>
<!ELEMENT nomfil (#PCDATA)>
<!ELEMENT etudiant (nom, prenom, email, reponse)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT reponse (#PCDATA)>
<!ELEMENT Observation (#PCDATA)>

=== Aminos7/XML-Database-Mobilit-/ProjetXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mobilités SYSTEM "file:/C:/Users/DELL/Desktop/ProjetDTD.dtd">
<Mobilités>
  <offre>
    <Ecolepartenaire>Université de Nice</Ecolepartenaire>
    <Option>
      <Parcours>Science in Ubiquitous Networking and computing</Parcours>
      <NbPlaces>7</NbPlaces>
      <TypeMobilité>Master</TypeMobilité>
      <INPT>
        <filliere>
          <nomfil>SUD</nomfil>
          <etudiant>
            <nom>Bouanani</nom>
            <prenom>Hajar</prenom>
            <email>hajar.bouanani@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>AMOA</nomfil>
          <etudiant>
            <nom>Ghazouani</nom>
            <prenom>Imad</prenom>
            <email>imad.ghazouani@gmail.com</email>
            <reponse>Non Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>DATA</nomfil>
          <etudiant>
            <nom>Lachkar</nom>
            <prenom>Oussama</prenom>
            <email>oussama.lachkar@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>ASEDS</nomfil>
          <etudiant>
            <nom>Bouchibti</nom>
            <prenom>Marwane</prenom>
            <email>marwane.bouchibti@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>SMART</nomfil>
          <etudiant>
            <nom>Barakat</nom>
            <prenom>Rajae</prenom>
            <email>rajae.barakat@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>SESNum</nomfil>
          <etudiant>
            <nom>Arfaoui</nom>
            <prenom>Najat</prenom>
            <email>najat.arfaoui@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>ICCN</nomfil>
          <etudiant>
            <nom>Roukh</nom>
            <prenom>Hicham</prenom>
            <email>hicham.roukh@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
      </INPT>
    </Option>
    <Observation>Candidature en ligne Deadline 31 mars</Observation>
  </offre>
  <offre>
    <Ecolepartenaire>UBO</Ecolepartenaire>
    <Option>
      <Parcours>Logiciels pour les Systèmes Embarqués</Parcours>
      <NbPlaces>5</NbPlaces>
      <TypeMobilité>Master</TypeMobilité>
      <INPT>
        <filliere>
          <nomfil>SESNum</nomfil>
          <etudiant>
            <nom>Hachimi</nom>
            <prenom>Yahya</prenom>
            <email>yahya.hachimi@gmail.com</email>
            <reponse>Non Admis</reponse>
          </etudiant>
          <etudiant>
            <nom>Achour</nom>
            <prenom>Souaad</prenom>
            <email>souaad.achour@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
          <etudiant>
            <nom>Bounou</nom>
            <prenom>Anouar</prenom>
            <email>anouar.bounou@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
          <etudiant>
            <nom>Idrissi</nom>
            <prenom>Mohammed</prenom>
            <email>mohammed.idrissi@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>ASEDS</nomfil>
          <etudiant>
            <nom>Kadmiri</nom>
            <prenom>Alae</prenom>
            <email>alae.kadmiri@gmail.com</email>
            <reponse>Non Admis</reponse>
          </etudiant>
        </filliere>
      </INPT>
    </Option>
    <Observation>Canditature via RI Deadline 31 mars</Observation>
  </offre>
  <offre>
    <Ecolepartenaire>INSA Rennes</Ecolepartenaire>
    <Option>
      <Parcours>Informatique</Parcours>
      <NbPlaces>2</NbPlaces>
      <TypeMobilité>Simple 2 semestres</TypeMobilité>
      <INPT>
        <filliere>
          <nomfil>ASEDS</nomfil>
          <etudiant>
            <nom>Ibrahimi</nom>
            <prenom>Saad</prenom>
            <email>saad.ibrahimi@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>SUD</nomfil>
          <etudiant>
            <nom>Chennani</nom>
            <prenom>Salwa</prenom>
            <email>salwa.chennani@gmail.com</email>
            <reponse>Non Admis</reponse>
          </etudiant>
        </filliere>
      </INPT>
    </Option>
    <Option>
      <Parcours>Génie mathématiques</Parcours>
      <NbPlaces>1</NbPlaces>
      <TypeMobilité>Simple 2 semestres</TypeMobilité>
      <INPT>
        <filliere>
          <nomfil>DATA</nomfil>
          <etudiant>
            <nom>Ayachi</nom>
            <prenom>Fahd</prenom>
            <email>fahd.ayachi@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
      </INPT>
    </Option>
    <Option>
      <Parcours>Systèmes et réseaux de communication</Parcours>
      <NbPlaces>2</NbPlaces>
      <TypeMobilité>Simple 2 semestres</TypeMobilité>
      <INPT>
        <filliere>
          <nomfil>SMART</nomfil>
          <etudiant>
            <nom>Salih</nom>
            <prenom>Mouaad</prenom>
            <email>mouaad.salih@gmail.com</email>
            <reponse>Non Admis</reponse>
          </etudiant>
          <etudiant>
            <nom>Bettioui</nom>
            <prenom>Achraf</prenom>
            <email>achraf.bettioui@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
      </INPT>
    </Option>
    <Option>
      <Parcours>Systèmes et réseaux de communication</Parcours>
      <NbPlaces>4</NbPlaces>
      <TypeMobilité>Double Diplomation</TypeMobilité>
      <INPT>
        <filliere>
          <nomfil>SMART</nomfil>
          <etudiant>
            <nom>Hajjouji</nom>
            <prenom>Salmane</prenom>
            <email>salmane hajjouji@gmail.com</email>
            <reponse>Non Admis</reponse>
          </etudiant>
          <etudiant>
            <nom>Zemmouri</nom>
            <prenom>Selma</prenom>
            <email>selma.zemmouri@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
          <etudiant>
            <nom>Boubrahimi</nom>
            <prenom>Azizi</prenom>
            <email>aziz.boubrahimi@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
          <etudiant>
            <nom>Elfarh</nom>
            <prenom>Driss</prenom>
            <email>driss.elfarh@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
      </INPT>
    </Option>
    <Observation>Canditature en ligne Deadline 31 mars</Observation>
  </offre>
  <offre>
    <Ecolepartenaire>IMT Atlantique</Ecolepartenaire>
    <Option>
      <Parcours>Informatique et réseaux</Parcours>
      <NbPlaces>4</NbPlaces>
      <TypeMobilité>Double Diplomation</TypeMobilité>
      <INPT>
        <filliere>
          <nomfil>ICCN</nomfil>
          <etudiant>
            <nom>Bouazza</nom>
            <prenom>Hamid</prenom>
            <email>hamid.bouazza@gmail.com</email>
            <reponse>Non Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>ASEDS</nomfil>
          <etudiant>
            <nom>Fatih</nom>
            <prenom>Yassmine</prenom>
            <email>yassmine.fatih@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>DATA</nomfil>
          <etudiant>
            <nom>Chaoui</nom>
            <prenom>Ahmed</prenom>
            <email>ahmed.chaoui@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>AMOA</nomfil>
          <etudiant>
            <nom>Taki</nom>
            <prenom>Oualid</prenom>
            <email>oualid.taki@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
      </INPT>
    </Option>
    <Option>
      <Parcours>Robotique électronique automatique télécommunications systèmes embarqués</Parcours>
      <NbPlaces>1</NbPlaces>
      <TypeMobilité>Simple 1 semestre</TypeMobilité>
      <INPT>
        <filliere>
          <nomfil>SESNum</nomfil>
          <etudiant>
            <nom>Tazi</nom>
            <prenom>Meryem</prenom>
            <email>meryem.tazi@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
      </INPT>
    </Option>
    <Option>
      <Parcours>Systèmes Industriels, organisations</Parcours>
      <NbPlaces>2</NbPlaces>
      <TypeMobilité>Double Diplomation</TypeMobilité>
      <INPT>
        <filliere>
          <nomfil>AMOA</nomfil>
          <etudiant>
            <nom>Benarfa</nom>
            <prenom>Hicham</prenom>
            <email>hicham.benarfa@gmail.com</email>
            <reponse>Non Admis</reponse>
          </etudiant>
        </filliere>
        <filliere>
          <nomfil>DATA</nomfil>
          <etudiant>
            <nom>Lehlou</nom>
            <prenom>Samir</prenom>
            <email>samir.lehlou@gmail.com</email>
            <reponse>Admis</reponse>
          </etudiant>
        </filliere>
      </INPT>
    </Option>
    <Observation>Canditature en ligne Deadline 31 mars</Observation>
  </offre>
  <offre>
    <Ecolepartenaire>Ensimag</Ecolepartenaire>
    <Option>
      <Parcours>Ingénierie des SI</Parcours>
      <NbPlaces>2</NbPlaces>
